/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppThreadIdRouteImport } from './routes/app.$threadId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTeamsAcceptInvitationRouteImport } from './routes/api/teams.accept-invitation'
import { Route as ApiProjectsWritebackReviewRouteImport } from './routes/api/projects.writeback-review'
import { Route as ApiProjectsWritebackExecuteRouteImport } from './routes/api/projects.writeback-execute'
import { Route as ApiProjectsWorkingCopyExportRouteImport } from './routes/api/projects.working-copy-export'
import { Route as ApiProjectsSnapshotExportRouteImport } from './routes/api/projects.snapshot-export'
import { Route as ApiProjectsSeedDemoRouteImport } from './routes/api/projects.seed-demo'
import { Route as ApiProjectsSandboxVerifyRouteImport } from './routes/api/projects.sandbox-verify'
import { Route as ApiProjectsSandboxJobsRouteImport } from './routes/api/projects.sandbox-jobs'
import { Route as ApiProjectsProcessZipRouteImport } from './routes/api/projects.process-zip'
import { Route as ApiProjectsGithubImportRouteImport } from './routes/api/projects.github-import'
import { Route as ApiProjectsAiProviderReadinessRouteImport } from './routes/api/projects.ai-provider-readiness'
import { Route as ApiProjectsAiPatchPreviewRouteImport } from './routes/api/projects.ai-patch-preview'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github.webhook'
import { Route as ApiGithubReposRouteImport } from './routes/api/github.repos'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github.install'
import { Route as ApiEnterpriseAuditExportRouteImport } from './routes/api/enterprise.audit-export'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing.webhook'
import { Route as ApiBillingCheckoutSessionRouteImport } from './routes/api/billing.checkout-session'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadIdRoute = AppThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsAcceptInvitationRoute =
  ApiTeamsAcceptInvitationRouteImport.update({
    id: '/api/teams/accept-invitation',
    path: '/api/teams/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsWritebackReviewRoute =
  ApiProjectsWritebackReviewRouteImport.update({
    id: '/api/projects/writeback-review',
    path: '/api/projects/writeback-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsWritebackExecuteRoute =
  ApiProjectsWritebackExecuteRouteImport.update({
    id: '/api/projects/writeback-execute',
    path: '/api/projects/writeback-execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsWorkingCopyExportRoute =
  ApiProjectsWorkingCopyExportRouteImport.update({
    id: '/api/projects/working-copy-export',
    path: '/api/projects/working-copy-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsSnapshotExportRoute =
  ApiProjectsSnapshotExportRouteImport.update({
    id: '/api/projects/snapshot-export',
    path: '/api/projects/snapshot-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsSeedDemoRoute = ApiProjectsSeedDemoRouteImport.update({
  id: '/api/projects/seed-demo',
  path: '/api/projects/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsSandboxVerifyRoute =
  ApiProjectsSandboxVerifyRouteImport.update({
    id: '/api/projects/sandbox-verify',
    path: '/api/projects/sandbox-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsSandboxJobsRoute = ApiProjectsSandboxJobsRouteImport.update({
  id: '/api/projects/sandbox-jobs',
  path: '/api/projects/sandbox-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProcessZipRoute = ApiProjectsProcessZipRouteImport.update({
  id: '/api/projects/process-zip',
  path: '/api/projects/process-zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsGithubImportRoute = ApiProjectsGithubImportRouteImport.update({
  id: '/api/projects/github-import',
  path: '/api/projects/github-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsAiProviderReadinessRoute =
  ApiProjectsAiProviderReadinessRouteImport.update({
    id: '/api/projects/ai-provider-readiness',
    path: '/api/projects/ai-provider-readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsAiPatchPreviewRoute =
  ApiProjectsAiPatchPreviewRouteImport.update({
    id: '/api/projects/ai-patch-preview',
    path: '/api/projects/ai-patch-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnterpriseAuditExportRoute =
  ApiEnterpriseAuditExportRouteImport.update({
    id: '/api/enterprise/audit-export',
    path: '/api/enterprise/audit-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutSessionRoute =
  ApiBillingCheckoutSessionRouteImport.update({
    id: '/api/billing/checkout-session',
    path: '/api/billing/checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$threadId': typeof AppThreadIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/billing/checkout-session': typeof ApiBillingCheckoutSessionRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/enterprise/audit-export': typeof ApiEnterpriseAuditExportRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/projects/ai-patch-preview': typeof ApiProjectsAiPatchPreviewRoute
  '/api/projects/ai-provider-readiness': typeof ApiProjectsAiProviderReadinessRoute
  '/api/projects/github-import': typeof ApiProjectsGithubImportRoute
  '/api/projects/process-zip': typeof ApiProjectsProcessZipRoute
  '/api/projects/sandbox-jobs': typeof ApiProjectsSandboxJobsRoute
  '/api/projects/sandbox-verify': typeof ApiProjectsSandboxVerifyRoute
  '/api/projects/seed-demo': typeof ApiProjectsSeedDemoRoute
  '/api/projects/snapshot-export': typeof ApiProjectsSnapshotExportRoute
  '/api/projects/working-copy-export': typeof ApiProjectsWorkingCopyExportRoute
  '/api/projects/writeback-execute': typeof ApiProjectsWritebackExecuteRoute
  '/api/projects/writeback-review': typeof ApiProjectsWritebackReviewRoute
  '/api/teams/accept-invitation': typeof ApiTeamsAcceptInvitationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$threadId': typeof AppThreadIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/billing/checkout-session': typeof ApiBillingCheckoutSessionRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/enterprise/audit-export': typeof ApiEnterpriseAuditExportRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/projects/ai-patch-preview': typeof ApiProjectsAiPatchPreviewRoute
  '/api/projects/ai-provider-readiness': typeof ApiProjectsAiProviderReadinessRoute
  '/api/projects/github-import': typeof ApiProjectsGithubImportRoute
  '/api/projects/process-zip': typeof ApiProjectsProcessZipRoute
  '/api/projects/sandbox-jobs': typeof ApiProjectsSandboxJobsRoute
  '/api/projects/sandbox-verify': typeof ApiProjectsSandboxVerifyRoute
  '/api/projects/seed-demo': typeof ApiProjectsSeedDemoRoute
  '/api/projects/snapshot-export': typeof ApiProjectsSnapshotExportRoute
  '/api/projects/working-copy-export': typeof ApiProjectsWorkingCopyExportRoute
  '/api/projects/writeback-execute': typeof ApiProjectsWritebackExecuteRoute
  '/api/projects/writeback-review': typeof ApiProjectsWritebackReviewRoute
  '/api/teams/accept-invitation': typeof ApiTeamsAcceptInvitationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$threadId': typeof AppThreadIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/billing/checkout-session': typeof ApiBillingCheckoutSessionRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/enterprise/audit-export': typeof ApiEnterpriseAuditExportRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/projects/ai-patch-preview': typeof ApiProjectsAiPatchPreviewRoute
  '/api/projects/ai-provider-readiness': typeof ApiProjectsAiProviderReadinessRoute
  '/api/projects/github-import': typeof ApiProjectsGithubImportRoute
  '/api/projects/process-zip': typeof ApiProjectsProcessZipRoute
  '/api/projects/sandbox-jobs': typeof ApiProjectsSandboxJobsRoute
  '/api/projects/sandbox-verify': typeof ApiProjectsSandboxVerifyRoute
  '/api/projects/seed-demo': typeof ApiProjectsSeedDemoRoute
  '/api/projects/snapshot-export': typeof ApiProjectsSnapshotExportRoute
  '/api/projects/working-copy-export': typeof ApiProjectsWorkingCopyExportRoute
  '/api/projects/writeback-execute': typeof ApiProjectsWritebackExecuteRoute
  '/api/projects/writeback-review': typeof ApiProjectsWritebackReviewRoute
  '/api/teams/accept-invitation': typeof ApiTeamsAcceptInvitationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/api/health'
    | '/app/$threadId'
    | '/app/admin'
    | '/app/settings'
    | '/app/'
    | '/api/billing/checkout-session'
    | '/api/billing/webhook'
    | '/api/enterprise/audit-export'
    | '/api/github/install'
    | '/api/github/repos'
    | '/api/github/webhook'
    | '/api/projects/ai-patch-preview'
    | '/api/projects/ai-provider-readiness'
    | '/api/projects/github-import'
    | '/api/projects/process-zip'
    | '/api/projects/sandbox-jobs'
    | '/api/projects/sandbox-verify'
    | '/api/projects/seed-demo'
    | '/api/projects/snapshot-export'
    | '/api/projects/working-copy-export'
    | '/api/projects/writeback-execute'
    | '/api/projects/writeback-review'
    | '/api/teams/accept-invitation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/api/health'
    | '/app/$threadId'
    | '/app/admin'
    | '/app/settings'
    | '/app'
    | '/api/billing/checkout-session'
    | '/api/billing/webhook'
    | '/api/enterprise/audit-export'
    | '/api/github/install'
    | '/api/github/repos'
    | '/api/github/webhook'
    | '/api/projects/ai-patch-preview'
    | '/api/projects/ai-provider-readiness'
    | '/api/projects/github-import'
    | '/api/projects/process-zip'
    | '/api/projects/sandbox-jobs'
    | '/api/projects/sandbox-verify'
    | '/api/projects/seed-demo'
    | '/api/projects/snapshot-export'
    | '/api/projects/working-copy-export'
    | '/api/projects/writeback-execute'
    | '/api/projects/writeback-review'
    | '/api/teams/accept-invitation'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/api/health'
    | '/app/$threadId'
    | '/app/admin'
    | '/app/settings'
    | '/app/'
    | '/api/billing/checkout-session'
    | '/api/billing/webhook'
    | '/api/enterprise/audit-export'
    | '/api/github/install'
    | '/api/github/repos'
    | '/api/github/webhook'
    | '/api/projects/ai-patch-preview'
    | '/api/projects/ai-provider-readiness'
    | '/api/projects/github-import'
    | '/api/projects/process-zip'
    | '/api/projects/sandbox-jobs'
    | '/api/projects/sandbox-verify'
    | '/api/projects/seed-demo'
    | '/api/projects/snapshot-export'
    | '/api/projects/working-copy-export'
    | '/api/projects/writeback-execute'
    | '/api/projects/writeback-review'
    | '/api/teams/accept-invitation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiBillingCheckoutSessionRoute: typeof ApiBillingCheckoutSessionRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiEnterpriseAuditExportRoute: typeof ApiEnterpriseAuditExportRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiProjectsAiPatchPreviewRoute: typeof ApiProjectsAiPatchPreviewRoute
  ApiProjectsAiProviderReadinessRoute: typeof ApiProjectsAiProviderReadinessRoute
  ApiProjectsGithubImportRoute: typeof ApiProjectsGithubImportRoute
  ApiProjectsProcessZipRoute: typeof ApiProjectsProcessZipRoute
  ApiProjectsSandboxJobsRoute: typeof ApiProjectsSandboxJobsRoute
  ApiProjectsSandboxVerifyRoute: typeof ApiProjectsSandboxVerifyRoute
  ApiProjectsSeedDemoRoute: typeof ApiProjectsSeedDemoRoute
  ApiProjectsSnapshotExportRoute: typeof ApiProjectsSnapshotExportRoute
  ApiProjectsWorkingCopyExportRoute: typeof ApiProjectsWorkingCopyExportRoute
  ApiProjectsWritebackExecuteRoute: typeof ApiProjectsWritebackExecuteRoute
  ApiProjectsWritebackReviewRoute: typeof ApiProjectsWritebackReviewRoute
  ApiTeamsAcceptInvitationRoute: typeof ApiTeamsAcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$threadId': {
      id: '/app/$threadId'
      path: '/$threadId'
      fullPath: '/app/$threadId'
      preLoaderRoute: typeof AppThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams/accept-invitation': {
      id: '/api/teams/accept-invitation'
      path: '/api/teams/accept-invitation'
      fullPath: '/api/teams/accept-invitation'
      preLoaderRoute: typeof ApiTeamsAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/writeback-review': {
      id: '/api/projects/writeback-review'
      path: '/api/projects/writeback-review'
      fullPath: '/api/projects/writeback-review'
      preLoaderRoute: typeof ApiProjectsWritebackReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/writeback-execute': {
      id: '/api/projects/writeback-execute'
      path: '/api/projects/writeback-execute'
      fullPath: '/api/projects/writeback-execute'
      preLoaderRoute: typeof ApiProjectsWritebackExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/working-copy-export': {
      id: '/api/projects/working-copy-export'
      path: '/api/projects/working-copy-export'
      fullPath: '/api/projects/working-copy-export'
      preLoaderRoute: typeof ApiProjectsWorkingCopyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/snapshot-export': {
      id: '/api/projects/snapshot-export'
      path: '/api/projects/snapshot-export'
      fullPath: '/api/projects/snapshot-export'
      preLoaderRoute: typeof ApiProjectsSnapshotExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/seed-demo': {
      id: '/api/projects/seed-demo'
      path: '/api/projects/seed-demo'
      fullPath: '/api/projects/seed-demo'
      preLoaderRoute: typeof ApiProjectsSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/sandbox-verify': {
      id: '/api/projects/sandbox-verify'
      path: '/api/projects/sandbox-verify'
      fullPath: '/api/projects/sandbox-verify'
      preLoaderRoute: typeof ApiProjectsSandboxVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/sandbox-jobs': {
      id: '/api/projects/sandbox-jobs'
      path: '/api/projects/sandbox-jobs'
      fullPath: '/api/projects/sandbox-jobs'
      preLoaderRoute: typeof ApiProjectsSandboxJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/process-zip': {
      id: '/api/projects/process-zip'
      path: '/api/projects/process-zip'
      fullPath: '/api/projects/process-zip'
      preLoaderRoute: typeof ApiProjectsProcessZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/github-import': {
      id: '/api/projects/github-import'
      path: '/api/projects/github-import'
      fullPath: '/api/projects/github-import'
      preLoaderRoute: typeof ApiProjectsGithubImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/ai-provider-readiness': {
      id: '/api/projects/ai-provider-readiness'
      path: '/api/projects/ai-provider-readiness'
      fullPath: '/api/projects/ai-provider-readiness'
      preLoaderRoute: typeof ApiProjectsAiProviderReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/ai-patch-preview': {
      id: '/api/projects/ai-patch-preview'
      path: '/api/projects/ai-patch-preview'
      fullPath: '/api/projects/ai-patch-preview'
      preLoaderRoute: typeof ApiProjectsAiPatchPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enterprise/audit-export': {
      id: '/api/enterprise/audit-export'
      path: '/api/enterprise/audit-export'
      fullPath: '/api/enterprise/audit-export'
      preLoaderRoute: typeof ApiEnterpriseAuditExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout-session': {
      id: '/api/billing/checkout-session'
      path: '/api/billing/checkout-session'
      fullPath: '/api/billing/checkout-session'
      preLoaderRoute: typeof ApiBillingCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppThreadIdRoute: typeof AppThreadIdRoute
  AppAdminRoute: typeof AppAdminRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppThreadIdRoute: AppThreadIdRoute,
  AppAdminRoute: AppAdminRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiBillingCheckoutSessionRoute: ApiBillingCheckoutSessionRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiEnterpriseAuditExportRoute: ApiEnterpriseAuditExportRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiProjectsAiPatchPreviewRoute: ApiProjectsAiPatchPreviewRoute,
  ApiProjectsAiProviderReadinessRoute: ApiProjectsAiProviderReadinessRoute,
  ApiProjectsGithubImportRoute: ApiProjectsGithubImportRoute,
  ApiProjectsProcessZipRoute: ApiProjectsProcessZipRoute,
  ApiProjectsSandboxJobsRoute: ApiProjectsSandboxJobsRoute,
  ApiProjectsSandboxVerifyRoute: ApiProjectsSandboxVerifyRoute,
  ApiProjectsSeedDemoRoute: ApiProjectsSeedDemoRoute,
  ApiProjectsSnapshotExportRoute: ApiProjectsSnapshotExportRoute,
  ApiProjectsWorkingCopyExportRoute: ApiProjectsWorkingCopyExportRoute,
  ApiProjectsWritebackExecuteRoute: ApiProjectsWritebackExecuteRoute,
  ApiProjectsWritebackReviewRoute: ApiProjectsWritebackReviewRoute,
  ApiTeamsAcceptInvitationRoute: ApiTeamsAcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
