/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppThreadIdRouteImport } from './routes/app.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiProjectsWritebackReviewRouteImport } from './routes/api/projects.writeback-review'
import { Route as ApiProjectsWritebackExecuteRouteImport } from './routes/api/projects.writeback-execute'
import { Route as ApiProjectsWorkingCopyExportRouteImport } from './routes/api/projects.working-copy-export'
import { Route as ApiProjectsSnapshotExportRouteImport } from './routes/api/projects.snapshot-export'
import { Route as ApiProjectsProcessZipRouteImport } from './routes/api/projects.process-zip'
import { Route as ApiProjectsAiPatchPreviewRouteImport } from './routes/api/projects.ai-patch-preview'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadIdRoute = AppThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsWritebackReviewRoute =
  ApiProjectsWritebackReviewRouteImport.update({
    id: '/api/projects/writeback-review',
    path: '/api/projects/writeback-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsWritebackExecuteRoute =
  ApiProjectsWritebackExecuteRouteImport.update({
    id: '/api/projects/writeback-execute',
    path: '/api/projects/writeback-execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsWorkingCopyExportRoute =
  ApiProjectsWorkingCopyExportRouteImport.update({
    id: '/api/projects/working-copy-export',
    path: '/api/projects/working-copy-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsSnapshotExportRoute =
  ApiProjectsSnapshotExportRouteImport.update({
    id: '/api/projects/snapshot-export',
    path: '/api/projects/snapshot-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProcessZipRoute = ApiProjectsProcessZipRouteImport.update({
  id: '/api/projects/process-zip',
  path: '/api/projects/process-zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsAiPatchPreviewRoute =
  ApiProjectsAiPatchPreviewRouteImport.update({
    id: '/api/projects/ai-patch-preview',
    path: '/api/projects/ai-patch-preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/$threadId': typeof AppThreadIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/projects/ai-patch-preview': typeof ApiProjectsAiPatchPreviewRoute
  '/api/projects/process-zip': typeof ApiProjectsProcessZipRoute
  '/api/projects/snapshot-export': typeof ApiProjectsSnapshotExportRoute
  '/api/projects/working-copy-export': typeof ApiProjectsWorkingCopyExportRoute
  '/api/projects/writeback-execute': typeof ApiProjectsWritebackExecuteRoute
  '/api/projects/writeback-review': typeof ApiProjectsWritebackReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/$threadId': typeof AppThreadIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/projects/ai-patch-preview': typeof ApiProjectsAiPatchPreviewRoute
  '/api/projects/process-zip': typeof ApiProjectsProcessZipRoute
  '/api/projects/snapshot-export': typeof ApiProjectsSnapshotExportRoute
  '/api/projects/working-copy-export': typeof ApiProjectsWorkingCopyExportRoute
  '/api/projects/writeback-execute': typeof ApiProjectsWritebackExecuteRoute
  '/api/projects/writeback-review': typeof ApiProjectsWritebackReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/$threadId': typeof AppThreadIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/projects/ai-patch-preview': typeof ApiProjectsAiPatchPreviewRoute
  '/api/projects/process-zip': typeof ApiProjectsProcessZipRoute
  '/api/projects/snapshot-export': typeof ApiProjectsSnapshotExportRoute
  '/api/projects/working-copy-export': typeof ApiProjectsWorkingCopyExportRoute
  '/api/projects/writeback-execute': typeof ApiProjectsWritebackExecuteRoute
  '/api/projects/writeback-review': typeof ApiProjectsWritebackReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/$threadId'
    | '/app/admin'
    | '/app/settings'
    | '/app/'
    | '/api/projects/ai-patch-preview'
    | '/api/projects/process-zip'
    | '/api/projects/snapshot-export'
    | '/api/projects/working-copy-export'
    | '/api/projects/writeback-execute'
    | '/api/projects/writeback-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/$threadId'
    | '/app/admin'
    | '/app/settings'
    | '/app'
    | '/api/projects/ai-patch-preview'
    | '/api/projects/process-zip'
    | '/api/projects/snapshot-export'
    | '/api/projects/working-copy-export'
    | '/api/projects/writeback-execute'
    | '/api/projects/writeback-review'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/app/$threadId'
    | '/app/admin'
    | '/app/settings'
    | '/app/'
    | '/api/projects/ai-patch-preview'
    | '/api/projects/process-zip'
    | '/api/projects/snapshot-export'
    | '/api/projects/working-copy-export'
    | '/api/projects/writeback-execute'
    | '/api/projects/writeback-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiProjectsAiPatchPreviewRoute: typeof ApiProjectsAiPatchPreviewRoute
  ApiProjectsProcessZipRoute: typeof ApiProjectsProcessZipRoute
  ApiProjectsSnapshotExportRoute: typeof ApiProjectsSnapshotExportRoute
  ApiProjectsWorkingCopyExportRoute: typeof ApiProjectsWorkingCopyExportRoute
  ApiProjectsWritebackExecuteRoute: typeof ApiProjectsWritebackExecuteRoute
  ApiProjectsWritebackReviewRoute: typeof ApiProjectsWritebackReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$threadId': {
      id: '/app/$threadId'
      path: '/$threadId'
      fullPath: '/app/$threadId'
      preLoaderRoute: typeof AppThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/writeback-review': {
      id: '/api/projects/writeback-review'
      path: '/api/projects/writeback-review'
      fullPath: '/api/projects/writeback-review'
      preLoaderRoute: typeof ApiProjectsWritebackReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/writeback-execute': {
      id: '/api/projects/writeback-execute'
      path: '/api/projects/writeback-execute'
      fullPath: '/api/projects/writeback-execute'
      preLoaderRoute: typeof ApiProjectsWritebackExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/working-copy-export': {
      id: '/api/projects/working-copy-export'
      path: '/api/projects/working-copy-export'
      fullPath: '/api/projects/working-copy-export'
      preLoaderRoute: typeof ApiProjectsWorkingCopyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/snapshot-export': {
      id: '/api/projects/snapshot-export'
      path: '/api/projects/snapshot-export'
      fullPath: '/api/projects/snapshot-export'
      preLoaderRoute: typeof ApiProjectsSnapshotExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/process-zip': {
      id: '/api/projects/process-zip'
      path: '/api/projects/process-zip'
      fullPath: '/api/projects/process-zip'
      preLoaderRoute: typeof ApiProjectsProcessZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/ai-patch-preview': {
      id: '/api/projects/ai-patch-preview'
      path: '/api/projects/ai-patch-preview'
      fullPath: '/api/projects/ai-patch-preview'
      preLoaderRoute: typeof ApiProjectsAiPatchPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppThreadIdRoute: typeof AppThreadIdRoute
  AppAdminRoute: typeof AppAdminRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppThreadIdRoute: AppThreadIdRoute,
  AppAdminRoute: AppAdminRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  ApiProjectsAiPatchPreviewRoute: ApiProjectsAiPatchPreviewRoute,
  ApiProjectsProcessZipRoute: ApiProjectsProcessZipRoute,
  ApiProjectsSnapshotExportRoute: ApiProjectsSnapshotExportRoute,
  ApiProjectsWorkingCopyExportRoute: ApiProjectsWorkingCopyExportRoute,
  ApiProjectsWritebackExecuteRoute: ApiProjectsWritebackExecuteRoute,
  ApiProjectsWritebackReviewRoute: ApiProjectsWritebackReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
