// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  const viteEnv = import.meta.env as Record<string, string | undefined>;
  const processEnv = typeof process !== "undefined" ? process.env : {};

  // Use Vite-injected env first, then SSR/runtime env aliases used by Lovable.
  const SUPABASE_URL = viteEnv.VITE_SUPABASE_URL || viteEnv.SUPABASE_URL || processEnv.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    viteEnv.SUPABASE_PUBLISHABLE_KEY ||
    viteEnv.VITE_SUPABASE_ANON_KEY ||
    viteEnv.SUPABASE_ANON_KEY ||
    processEnv.SUPABASE_PUBLISHABLE_KEY ||
    processEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    processEnv.SUPABASE_ANON_KEY ||
    processEnv.VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY or SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
